### ISSUE TITLE
Is this Django 1.8 ready?

### ISSUE THREAD

**Issue by psychok7** [lukaszb/django-guardian#313]
I have never used django-guardian, and i am about to start a new project using Django 1.8 and was thinking about using it. 

i see many issues regarding erros when testing with Django 1.8 so my question is should i be using this right away? If not how long more or less till the official 1.8 version??

thanks guys

**Comment by HEdingfield** [comment]
Agreed, wondering what the timeline is for a 1.8-ready release?

**Comment by cyber778** [comment]
+1

**Comment by spectras** [comment]
That would be great indeed, that's the only module that's preventing me from migrating to 1.8 now.
(hi psychok7 ^^)

**Comment by pcamelo** [comment]
+1

**Comment by Gank** [comment]
+1

**Comment by semeano** [comment]
+1

**Comment by troygrosfield** [comment]
@lukaszb, what's the 1.8 status?  I see that travis is successfully passing against 1.8.  When can we expect a release?  

Thanks in advance!

**Comment by avelis** [comment]
+1 as well.

So, by assessing the source. The project is 1.8 ready but there is no release in pypi for anyone to consume it. If you want you can install the project via source.

**Comment by gsekando** [comment]
+1

**Comment by odedbd** [comment]
+1

**Comment by trungdong** [comment]
+1

**Comment by StenAkeStrid** [comment]
+1

**Comment by Zundrium** [comment]
+1

**Comment by troygrosfield** [comment]
I believe the release of django-guardian 1.3 that happened 22 days ago contained all the necessary django 1.8 changes. I'm currently using it in production with django 1.8.2, python 3.4.3 without issues.

**Comment by psychok7** [comment]
Thanks for the info @troygrosfield im going to close this issue then

**Comment by troygrosfield** [comment]
Circling back around, here's the PRs that did it (among others):

- https://github.com/lukaszb/django-guardian/pull/306
- https://github.com/lukaszb/django-guardian/pull/311
